# Generated by Django 5.1.3 on 2025-02-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DashBorad',
            new_name='DashBoard',
        ),
    ]
