# Generated by Django 5.1.3 on 2025-02-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0002_rename_dashborad_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
