# Generated by Django 5.1.4 on 2025-01-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CUJO', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='personal_id',
        ),
    ]
