# Generated by Django 5.1.4 on 2025-01-30 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUJO', '0004_remove_user_personal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdash',
            name='author',
        ),
        migrations.AddField(
            model_name='postdash',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
