# Generated by Django 5.1.4 on 2025-01-31 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUJO', '0006_remove_comment_author_remove_comment_dash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdash',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
