# Generated by Django 5.1.4 on 2025-01-31 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUJO', '0007_alter_postdash_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdash',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
