# Generated by Django 5.1.4 on 2025-01-31 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUJO', '0008_alter_postdash_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdash',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='dash',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CUJO.postdash'),
            preserve_default=False,
        ),
    ]
