# Generated by Django 5.1.4 on 2025-02-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CUJO', '0009_remove_postdash_comment_comment_dash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='main',
            new_name='mains',
        ),
    ]
