# Generated by Django 5.1.4 on 2025-02-01 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUJO', '0010_delete_author_rename_main_comment_mains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dash',
        ),
        migrations.AddField(
            model_name='postdash',
            name='comment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CUJO.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
