# Generated by Django 5.1.4 on 2025-02-01 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUJO', '0011_remove_comment_dash_postdash_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdash',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='dash',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CUJO.postdash'),
        ),
    ]
