# Generated by Django 5.1.4 on 2025-02-03 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUJO', '0012_remove_postdash_comment_comment_dash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='unlike',
        ),
        migrations.RemoveField(
            model_name='postdash',
            name='like',
        ),
        migrations.RemoveField(
            model_name='postdash',
            name='unlike',
        ),
        migrations.AddField(
            model_name='comment',
            name='like_users',
            field=models.ManyToManyField(related_name='like_da', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postdash',
            name='like_users',
            field=models.ManyToManyField(related_name='like_dash', to=settings.AUTH_USER_MODEL),
        ),
    ]
