# Generated by Django 5.1.4 on 2025-02-03 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUJO', '0013_remove_comment_like_remove_comment_unlike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislike_users',
            field=models.ManyToManyField(related_name='dislike_da', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postdash',
            name='dislike_users',
            field=models.ManyToManyField(related_name='dislike_dash', to=settings.AUTH_USER_MODEL),
        ),
    ]
